# Generated by Django 2.0.5 on 2019-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testproject', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('testmodule', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('testpage', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('zjysinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入增加预算的内容')),
                ('ffzt', models.CharField(blank=True, default='', help_text='1表示开启，否则为关闭', max_length=100, null=True, verbose_name='输入发放状态的单选的内容')),
                ('zjkcinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入增加库存的内容')),
                ('isqcancel', models.BooleanField(default=False, verbose_name='是否点击券页取消按钮')),
                ('iscancel', models.BooleanField(default=False, verbose_name='是否点击取消按钮')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '添加进行中的活动的测试数据',
                'verbose_name_plural': '添加进行中的活动的测试数据',
            },
        ),
    ]
