# Generated by Django 2.0.5 on 2019-07-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0003_auto_20190704_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportimage',
            field=models.ImageField(height_field='image_height', upload_to='report/%Y%m/screenshop/', verbose_name='报告中错误截图', width_field='image_width'),
        ),
    ]
