# Generated by Django 2.0.5 on 2019-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0005_report_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.AlterField(
            model_name='report',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='50', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='50', editable=False, null=True),
        ),
    ]
