# Generated by Django 2.0.5 on 2019-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0006_auto_20190704_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportfile',
            field=models.FileField(max_length=1000, upload_to='report/%Y%m', verbose_name='报告文件'),
        ),
    ]
