# Generated by Django 2.0.5 on 2019-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0007_auto_20190704_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportimage',
            field=models.ImageField(height_field='image_height', max_length=1000, upload_to='report/%Y%m/screenshop/', verbose_name='报告中错误截图', width_field='image_width'),
        ),
    ]
