# Generated by Django 2.0.5 on 2019-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0009_auto_20190704_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='report',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportimage',
        ),
        migrations.AlterField(
            model_name='report',
            name='reportname',
            field=models.CharField(default='', max_length=100, verbose_name='自动化开始执行时间串'),
        ),
    ]
