# Generated by Django 2.0.5 on 2019-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0010_auto_20190704_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportname',
            field=models.CharField(default='', max_length=15, verbose_name='自动化开始执行时间串'),
        ),
    ]
