# Generated by Django 2.0.5 on 2019-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0014_auto_20190704_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportfile',
            field=models.FileField(editable=False, max_length=1000, upload_to='report/%Y%m', verbose_name='报告文件'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportname',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='测试执行开始时间串'),
        ),
    ]
