# Generated by Django 2.0.5 on 2019-07-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportrecord', '0016_auto_20190704_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='testmodule',
            field=models.CharField(default='', max_length=50, verbose_name='项目模块'),
        ),
        migrations.AddField(
            model_name='report',
            name='testproject',
            field=models.CharField(default='', max_length=50, verbose_name='测试项目'),
        ),
    ]
