# Generated by Django 2.0.5 on 2019-01-17 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EleTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_data', models.CharField(default='', max_length=1000, verbose_name='元素测试数据')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '元素测试数据',
                'verbose_name_plural': '元素测试数据',
            },
        ),
        migrations.CreateModel(
            name='EleTestDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_data_type', models.CharField(default='', max_length=100, verbose_name='测试数据类型')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '元素测试数据类型',
                'verbose_name_plural': '元素测试数据类型',
            },
        ),
        migrations.CreateModel(
            name='ModulePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ele_page', models.CharField(default='', max_length=100, verbose_name='元素页面')),
                ('ele_page_url', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='元素页面URL')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加页面时间')),
            ],
            options={
                'verbose_name': '模块页面',
                'verbose_name_plural': '模块页面',
            },
        ),
        migrations.CreateModel(
            name='PageEle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ele_name', models.CharField(default='', max_length=100, verbose_name='元素名字')),
                ('ele_xpath', models.CharField(default='', max_length=1000, verbose_name='元素xpath路径')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('modulepage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.ModulePage', verbose_name='模块页面')),
            ],
            options={
                'verbose_name': '页面元素',
                'verbose_name_plural': '页面元素',
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_module', models.CharField(default='', max_length=100, verbose_name='项目模块')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加模块时间')),
            ],
            options={
                'verbose_name': '项目模块',
                'verbose_name_plural': '项目模块',
            },
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_project', models.CharField(default='', max_length=100, verbose_name='web项目')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加项目时间')),
            ],
            options={
                'verbose_name': '测试项目',
                'verbose_name_plural': '测试项目',
            },
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='testproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.TestProject', verbose_name='测试项目'),
        ),
        migrations.AddField(
            model_name='pageele',
            name='projectmodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.ProjectModule', verbose_name='项目模块'),
        ),
        migrations.AddField(
            model_name='pageele',
            name='testproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.TestProject', verbose_name='测试项目'),
        ),
        migrations.AddField(
            model_name='modulepage',
            name='projectmodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.ProjectModule', verbose_name='项目模块'),
        ),
        migrations.AddField(
            model_name='modulepage',
            name='testproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.TestProject', verbose_name='测试项目'),
        ),
        migrations.AddField(
            model_name='eletestdatatype',
            name='modulepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.ModulePage', verbose_name='模块页面'),
        ),
        migrations.AddField(
            model_name='eletestdatatype',
            name='pageele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.PageEle', verbose_name='页面元素'),
        ),
        migrations.AddField(
            model_name='eletestdatatype',
            name='projectmodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.ProjectModule', verbose_name='项目模块'),
        ),
        migrations.AddField(
            model_name='eletestdatatype',
            name='testproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.TestProject', verbose_name='测试项目'),
        ),
        migrations.AddField(
            model_name='eletestdata',
            name='eletestdatatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.EleTestDataType', verbose_name='元素测试数据类型'),
        ),
        migrations.AddField(
            model_name='eletestdata',
            name='modulepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.ModulePage', verbose_name='模块页面'),
        ),
        migrations.AddField(
            model_name='eletestdata',
            name='pageele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.PageEle', verbose_name='页面元素'),
        ),
        migrations.AddField(
            model_name='eletestdata',
            name='projectmodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.ProjectModule', verbose_name='项目模块'),
        ),
        migrations.AddField(
            model_name='eletestdata',
            name='testproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageelement.TestProject', verbose_name='测试项目'),
        ),
    ]
