# Generated by Django 2.0.5 on 2019-01-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageelement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproject',
            name='web_project',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='web项目'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmodule',
            unique_together={('testproject', 'web_module')},
        ),
    ]
