# Generated by Django 2.0.5 on 2019-01-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageelement', '0002_auto_20190121_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulepage',
            unique_together={('testproject', 'projectmodule', 'ele_page')},
        ),
    ]
