# Generated by Django 2.0.5 on 2019-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageelement', '0003_auto_20190121_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='web_module',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='项目模块'),
        ),
    ]
