# Generated by Django 2.0.5 on 2019-01-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageelement', '0004_auto_20190121_1630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmodule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projectmodule',
            name='testproject',
        ),
    ]
