# Generated by Django 2.0.5 on 2019-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageelement', '0006_auto_20190121_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageele',
            name='projectmodule',
        ),
        migrations.RemoveField(
            model_name='pageele',
            name='testproject',
        ),
    ]
