# Generated by Django 2.0.5 on 2019-01-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageelement', '0008_auto_20190121_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletestdata',
            name='modulepage',
        ),
    ]
