# Generated by Django 2.0.5 on 2019-04-11 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webproject', models.CharField(default='', max_length=100, verbose_name='web后台项目')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('brandnameinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('emailinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('contactnumberinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('merchanttypeselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('categoryselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('criteriaselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('siupinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('provinceselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('cityselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('districtinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('villageinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('postcodeinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('photosiupimagefilepath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('photonpwpcompanyimagefilepath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('phototdpimagefilepath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('nameinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('npwpinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('typeidselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('identitynumberinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('address2inputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('nationalityselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('phoneinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('email2inputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('photofullfacebustimagefilepath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('locationphotoimagefilepath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('photoofthecashiersdeskimagefilepath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('otherphotoimagefilepath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('bankselectoptionxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径')),
                ('accountnameinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('accountnumberinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('qrindoaccountinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试内容的名称')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '添加商户测试数据',
                'verbose_name_plural': '添加商户测试数据',
            },
        ),
    ]
