# Generated by Django 2.0.5 on 2019-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmerchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmerchant',
            name='addressinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Address的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='accountnameinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Account name的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='accountnumberinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Account number的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='address2inputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Address的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='bankselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Bank选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='brandnameinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Brand name的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='categoryselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Category选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='cityselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='City选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='contactnumberinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Contact number的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='criteriaselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Criteria选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='districtinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入District的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='email2inputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Email的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='emailinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Email的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='identitynumberinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Identity number的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='locationphotoimagefilepath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='添加Location Photo图片的路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='merchanttypeselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Merchant type选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='nameinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Name的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='nationalityselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nationality选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='npwpinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入NPWP的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='otherphotoimagefilepath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='添加Other Photo图片的路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='phoneinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Phone的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='photofullfacebustimagefilepath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='添加Photo Full-faceBust图片的路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='photonpwpcompanyimagefilepath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='添加Photo NPWP Company图片的路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='photoofthecashiersdeskimagefilepath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='添加Photo of the cashiers desk图片的路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='photosiupimagefilepath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='添加Photo SIUP图片的路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='phototdpimagefilepath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='添加Photo TDP图片的路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='postcodeinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Postcode的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='provinceselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Province选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='qrindoaccountinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入QRindo account的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='siupinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入SIUP的内容'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='typeidselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Type ID选项内容Xpath路径'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='villageinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Village的内容'),
        ),
    ]
