# Generated by Django 2.0.5 on 2019-04-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmerchant', '0002_auto_20190411_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmerchant',
            name='companynameinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Company name的内容_公司商户'),
        ),
        migrations.AddField(
            model_name='addmerchant',
            name='iscompany',
            field=models.BooleanField(default=False, verbose_name='是否公司商户'),
        ),
        migrations.AddField(
            model_name='addmerchant',
            name='npwptaxidinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入NPWP/TAX ID的内容_公司商户'),
        ),
        migrations.AddField(
            model_name='addmerchant',
            name='officialwebsiteinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Official Website的内容_公司商户'),
        ),
        migrations.AddField(
            model_name='addmerchant',
            name='positioninputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Position的内容_公司商户'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='address2inputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Address的内容_个人商户'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='identitynumberinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入Identity number的内容_个人商户'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='nationalityselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nationality选项内容Xpath路径_个人商户'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='npwpinputtext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入NPWP的内容_个人商户'),
        ),
        migrations.AlterField(
            model_name='addmerchant',
            name='typeidselectoptionxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Type ID选项内容Xpath路径_个人商户'),
        ),
    ]
