# Generated by Django 2.0.5 on 2019-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webproject', models.CharField(default='', max_length=100, verbose_name='web后台项目')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('accountinput', models.CharField(default='', max_length=100, verbose_name='账号输入内容')),
                ('passwordinput', models.CharField(default='', max_length=100, verbose_name='密码输入内容')),
                ('vercodeinput', models.CharField(default='', max_length=100, verbose_name='验证码输入内容')),
                ('assertaccounttiptext', models.CharField(default='', max_length=100, verbose_name='账号提示内容')),
                ('assertpasswordtiptext', models.CharField(default='', max_length=100, verbose_name='密码提示内容')),
                ('assertvercodetiptext', models.CharField(default='', max_length=100, verbose_name='验证码提示内容')),
                ('assertlogintiptext', models.CharField(default='', max_length=100, verbose_name='点击登录提示内容')),
            ],
        ),
    ]
