# Generated by Django 2.0.5 on 2019-04-01 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logindata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加页面时间'),
        ),
    ]
