# Generated by Django 2.0.5 on 2019-04-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logindata', '0002_logindata_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logindata',
            options={'verbose_name': '登录测试数据', 'verbose_name_plural': '登录测试数据'},
        ),
    ]
