# Generated by Django 2.0.5 on 2019-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logindata', '0003_auto_20190401_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='accountinput',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='账号输入内容'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='assertaccounttiptext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='账号提示内容'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='assertlogintiptext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='点击登录提示内容'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='assertpasswordtiptext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='密码提示内容'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='assertvercodetiptext',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='验证码提示内容'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='passwordinput',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='密码输入内容'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='vercodeinput',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='验证码输入内容'),
        ),
    ]
