# Generated by Django 2.0.5 on 2019-01-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testfundata', '0002_testsearch_search_table_result_xpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsearch',
            name='check_text',
            field=models.CharField(default='', max_length=1000, verbose_name='check_text'),
        ),
        migrations.AlterField(
            model_name='testsearch',
            name='modulepage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='pageelement.ModulePage', verbose_name='模块页面'),
        ),
        migrations.AlterField(
            model_name='testsearch',
            name='search_table_result_xpath',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='strx', to='pageelement.PageEle', verbose_name='search_table_result_xpath'),
        ),
        migrations.AlterField(
            model_name='testsearch',
            name='select_input_xpath',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='six', to='pageelement.PageEle', verbose_name='select_input_xpath'),
        ),
        migrations.AlterField(
            model_name='testsearch',
            name='select_option_xpath',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sox', to='pageelement.PageEle', verbose_name='select_option_xpath'),
        ),
    ]
