# Generated by Django 2.0.5 on 2019-05-10 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testproject', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('testmodule', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('testpage', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('hdmcinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入活动名称的内容')),
                ('hdysinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入活动预算的内容')),
                ('tfqdyj', models.CharField(blank=True, default='', help_text='投放渠道一级为1表示内部渠道，为2表示外部渠道', max_length=100, null=True, verbose_name='输入投放渠道一级的选项的内容')),
                ('tfqdej', models.CharField(blank=True, default='', help_text='投放渠道二级为0表示全选，为1，2，等表示选一项和选多项组合，程序中只有全选和选择一项的情况', max_length=100, null=True, verbose_name='输入投放渠道二级的复选的内容')),
                ('hdbztextareainputtext', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='输入活动备注的内容')),
                ('rwlx', models.CharField(blank=True, default='', help_text='任务类型为1表示注册，为2表示交易类型', max_length=100, null=True, verbose_name='输入任务类型的选项的内容')),
                ('tjrwxz', models.CharField(blank=True, default='', help_text='1表示选择交易类型，2表示选择支付方式，3表示选择用户活动参与次数', max_length=100, null=True, verbose_name='输入点击添加任务弹窗中的选项的内容')),
                ('jyjylx', models.CharField(blank=True, default='', help_text='0表示选择所有项，1表示只选择消费，2表示只选择充值，3表示只选择转账', max_length=100, null=True, verbose_name='输入交易类型的复选的内容')),
                ('jyzffs', models.CharField(blank=True, default='', help_text='0表示选择所有项，1表示只选择钱包余额，2表示只选择银行卡', max_length=100, null=True, verbose_name='输入支付方式的复选的内容')),
                ('jymgyhzdcycsinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入每个用户最多参与次数的内容')),
                ('jymgyhmrcycsinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='输入每个用户每日参与次数的内容')),
                ('jllx', models.CharField(blank=True, default='', help_text='1表示固定奖励', max_length=100, null=True, verbose_name='输入选择奖励类型选项的内容')),
                ('iscancel', models.BooleanField(default=False, verbose_name='是否点击取消按钮')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '添加活动测试数据',
                'verbose_name_plural': '添加活动测试数据',
            },
        ),
    ]
