# Generated by Django 2.0.5 on 2019-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addactivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addactivity',
            name='hdbztextareainputtext',
            field=models.TextField(blank=True, default='', null=True, verbose_name='输入活动备注的内容'),
        ),
    ]
