# Generated by Django 2.0.5 on 2019-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addactivity', '0002_auto_20190510_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addactivity',
            name='hdbztextareainputtext',
            field=models.TextField(blank=True, default='', max_length=1025, null=True, verbose_name='输入活动备注的内容'),
        ),
    ]
