# Generated by Django 2.0.5 on 2019-05-10 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addactivity', '0003_auto_20190510_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addactivity',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间'),
        ),
    ]
