# Generated by Django 2.0.5 on 2019-04-02 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webproject', models.CharField(default='', max_length=100, verbose_name='web后台项目')),
                ('testpage', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('selectxpath', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='筛选字段选项Xpath路径')),
                ('selectoptiontext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='筛选字段选项内容')),
                ('selectinputxpath', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='筛选字段选项对应输入框的Xpath路径')),
                ('selectinputtext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='筛选字段选项对应输入框的输入内容')),
                ('colnum', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='搜索结果表格的列数')),
                ('checktext', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='搜索结果表格的列数对应的预期文本内容')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加页面时间')),
            ],
            options={
                'verbose_name': '检索测试数据',
                'verbose_name_plural': '检索测试数据',
            },
        ),
    ]
