# Generated by Django 2.0.5 on 2019-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdata',
            name='checktext',
            field=models.CharField(default='Corresponding data not queried!', max_length=100, verbose_name='搜索结果表格的列数对应的预期文本内容'),
        ),
        migrations.AlterField(
            model_name='searchdata',
            name='colnum',
            field=models.CharField(default='0', max_length=100, verbose_name='搜索结果表格的列数'),
        ),
        migrations.AlterField(
            model_name='searchdata',
            name='selectinputxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项对应输入框的Xpath路径'),
        ),
        migrations.AlterField(
            model_name='searchdata',
            name='selectxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项Xpath路径'),
        ),
    ]
