# Generated by Django 2.0.5 on 2019-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0002_auto_20190402_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchdata',
            name='selectoptiontext',
        ),
        migrations.AddField(
            model_name='searchdata',
            name='selectoptiontextxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项内容Xpath路径'),
        ),
    ]
