# Generated by Django 2.0.5 on 2019-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0003_auto_20190403_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdata',
            name='selectinputtext',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='筛选字段选项对应输入框的输入内容'),
        ),
    ]
