# Generated by Django 2.0.5 on 2019-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0004_auto_20190403_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='searchtableresultxpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选结果的Xpath路径'),
        ),
    ]
