# Generated by Django 2.0.5 on 2019-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0005_searchdata_searchtableresultxpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdata',
            name='searchtableresultxpath',
            field=models.CharField(default='', max_length=1000, verbose_name='筛选结果的Xpath路径'),
        ),
    ]
