# Generated by Django 2.0.5 on 2019-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0006_auto_20190403_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchdata',
            name='searchtableresultxpath',
        ),
        migrations.AddField(
            model_name='searchdata',
            name='isfind',
            field=models.BooleanField(default=False, verbose_name='筛选结果是否有相应内容'),
        ),
    ]
