# Generated by Django 2.0.5 on 2019-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0007_auto_20190403_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='selectinputselectonexpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='筛选字段选项对应输入框输入内容后下拉列表第一项的Xpath路径'),
        ),
    ]
