# Generated by Django 2.0.5 on 2019-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0008_searchdata_selectinputselectonexpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='isclicklastpage',
            field=models.BooleanField(default=False, verbose_name='是否点击最后一页页码'),
        ),
    ]
