# Generated by Django 2.0.5 on 2019-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputTipData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testproject', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('testmodule', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('testpage', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('isinput', models.BooleanField(default=False, verbose_name='是否输入内容')),
                ('inputxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='输入框Xpath路径')),
                ('inputtext', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='输入框的输入内容')),
                ('inputtipxpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='输入框下Tip提示信息Xpath路径')),
                ('inputtiptext', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='输入框下Tip提示信息内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '输入框提示测试数据',
                'verbose_name_plural': '输入框提示测试数据',
            },
        ),
    ]
