# Generated by Django 2.0.5 on 2019-08-01 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeminfoTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testproject', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('testmodule', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('testpage', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('forcount', models.CharField(default='', max_length=100, verbose_name='循环次数')),
                ('currentpagememinfo', models.CharField(blank=True, default='', help_text='当前页面内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面内存')),
                ('currentpageaftertenmeminfo', models.CharField(blank=True, default='', help_text='当前页面静置10秒后内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面静置10秒后内存')),
                ('clicknextpagememinfo', models.CharField(blank=True, default='', help_text='点击进入下一个页面内存（单位：KB）', max_length=100, null=True, verbose_name='点击进入下一个页面内存')),
                ('nextaftertenmeminfo', models.CharField(blank=True, default='', help_text='静置10秒后内存（单位：KB）', max_length=100, null=True, verbose_name='静置10秒后内存')),
                ('nextaftertenmeminfotwo', models.CharField(blank=True, default='', help_text='再次静置10秒后内存（单位：KB）', max_length=100, null=True, verbose_name='再次静置10秒后内存')),
                ('clickbackmeminfo', models.CharField(blank=True, default='', help_text='点击返回后内存（单位：KB）', max_length=100, null=True, verbose_name='点击返回后内存')),
                ('backaftertenmeminfo', models.CharField(blank=True, default='', help_text='静置10秒后内存（单位：KB）', max_length=100, null=True, verbose_name='静置10秒后内存')),
                ('backaftertenmeminfotwo', models.CharField(blank=True, default='', help_text='再次静置10秒后内存（单位：KB）', max_length=100, null=True, verbose_name='再次静置10秒后内存')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '内存测试结果统计',
                'verbose_name_plural': '内存测试结果统计',
            },
        ),
    ]
