# Generated by Django 2.0.5 on 2019-08-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0002_meminfotestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='meminfotestresult',
            name='teststarttime',
            field=models.CharField(default='', max_length=100, verbose_name='开始运行时间'),
        ),
    ]
