# Generated by Django 2.0.5 on 2019-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0003_meminfotestresult_teststarttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminfotestresult',
            name='forcount',
            field=models.CharField(default='', max_length=100, verbose_name='第几次循环'),
        ),
    ]
