# Generated by Django 2.0.5 on 2019-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0004_auto_20190801_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='meminfotestcase',
            name='currentstyleparame',
            field=models.CharField(default='', help_text='要点击元素查找风格的确切值', max_length=1000, verbose_name='要点击元素查找风格的确切值'),
        ),
        migrations.AddField(
            model_name='meminfotestcase',
            name='currrentfindstyle',
            field=models.CharField(default='', help_text='要点击元素查找风格，例如resourceId、text', max_length=100, verbose_name='要点击元素查找风格'),
        ),
    ]
