# Generated by Django 2.0.5 on 2019-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0005_auto_20190801_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='meminfotestresult',
            name='test_app_packagename',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试应用包名'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='test_app_version',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试应用版本号'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='test_phone_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试手机ID'),
        ),
    ]
