# Generated by Django 2.0.5 on 2019-08-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0006_auto_20190805_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='backaftertenmeminfo',
        ),
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='backaftertenmeminfotwo',
        ),
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='clickbackmeminfo',
        ),
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='clicknextpagememinfo',
        ),
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='currentpageaftertenmeminfo',
        ),
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='currentpagememinfo',
        ),
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='nextaftertenmeminfo',
        ),
        migrations.RemoveField(
            model_name='meminfotestresult',
            name='nextaftertenmeminfotwo',
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertenheapalloc',
            field=models.CharField(blank=True, default='', help_text='返回页静置10秒后Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='返回页静置10秒后Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertenheapfree',
            field=models.CharField(blank=True, default='', help_text='返回页静置10秒后Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='返回页静置10秒后Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertenheapsize',
            field=models.CharField(blank=True, default='', help_text='返回页静置10秒后Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='返回页静置10秒后Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertenobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='返回页静置10秒后Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='返回页静置10秒后Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertenobjectsviews',
            field=models.CharField(blank=True, default='', help_text='返回页静置10秒后Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='返回页静置10秒后Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertenpsstotal',
            field=models.CharField(blank=True, default='', help_text='返回页静置10秒后Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='返回页静置10秒后Pss Total内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertentwoheapalloc',
            field=models.CharField(blank=True, default='', help_text='返回页再次静置10秒后Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='返回页再次静置10秒后Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertentwoheapfree',
            field=models.CharField(blank=True, default='', help_text='返回页再次静置10秒后Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='返回页再次静置10秒后Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertentwoheapsize',
            field=models.CharField(blank=True, default='', help_text='返回页再次静置10秒后Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='返回页再次静置10秒后Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertentwoobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='返回页再次静置10秒后Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='返回页再次静置10秒后Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertentwoobjectsviews',
            field=models.CharField(blank=True, default='', help_text='返回页再次静置10秒后Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='返回页再次静置10秒后Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='backaftertentwopsstotal',
            field=models.CharField(blank=True, default='', help_text='返回页再次静置10秒后Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='返回页再次静置10秒后Pss Total内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='clickbackheapalloc',
            field=models.CharField(blank=True, default='', help_text='点击返回后Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='点击返回后Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='clickbackheapfree',
            field=models.CharField(blank=True, default='', help_text='点击返回后Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='点击返回后Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='clickbackheapsize',
            field=models.CharField(blank=True, default='', help_text='点击返回后Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='点击返回后Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='clickbackobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='点击返回后Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='点击返回后Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='clickbackobjectsviews',
            field=models.CharField(blank=True, default='', help_text='点击返回后Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='点击返回后Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='clickbackpsstotal',
            field=models.CharField(blank=True, default='', help_text='点击返回后Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='点击返回后Pss Total内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageaftertenheapalloc',
            field=models.CharField(blank=True, default='', help_text='当前页面静置10秒后Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面静置10秒后Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageaftertenheapfree',
            field=models.CharField(blank=True, default='', help_text='当前页面静置10秒后Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面静置10秒后Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageaftertenheapsize',
            field=models.CharField(blank=True, default='', help_text='当前页面静置10秒后Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面静置10秒后Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageaftertenobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='当前页面静置10秒后Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='当前页面静置10秒后Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageaftertenobjectsviews',
            field=models.CharField(blank=True, default='', help_text='当前页面静置10秒后Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='当前页面静置10秒后Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageaftertenpsstotal',
            field=models.CharField(blank=True, default='', help_text='当前页面静置10秒后Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面静置10秒后Pss Total内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageheapalloc',
            field=models.CharField(blank=True, default='', help_text='当前页面Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageheapfree',
            field=models.CharField(blank=True, default='', help_text='当前页面Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageheapsize',
            field=models.CharField(blank=True, default='', help_text='当前页面Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='当前页面Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='当前页面Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpageobjectsviews',
            field=models.CharField(blank=True, default='', help_text='当前页面Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='当前页面Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='currentpagepsstotal',
            field=models.CharField(blank=True, default='', help_text='当前页面Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='当前页面Pss Total内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='licknextpageheapalloc',
            field=models.CharField(blank=True, default='', help_text='点击进入下一个页面Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='点击进入下一个页面Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='licknextpageheapfree',
            field=models.CharField(blank=True, default='', help_text='点击进入下一个页面Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='点击进入下一个页面Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='licknextpageheapsize',
            field=models.CharField(blank=True, default='', help_text='点击进入下一个页面Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='点击进入下一个页面Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='licknextpageobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='点击进入下一个页面Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='点击进入下一个页面Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='licknextpageobjectsviews',
            field=models.CharField(blank=True, default='', help_text='点击进入下一个页面Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='点击进入下一个页面Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='licknextpagepsstotal',
            field=models.CharField(blank=True, default='', help_text='点击进入下一个页面Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='点击进入下一个页面Pss Total内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertenheapalloc',
            field=models.CharField(blank=True, default='', help_text='进入页静置10秒后Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='进入页静置10秒后Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertenheapfree',
            field=models.CharField(blank=True, default='', help_text='进入页静置10秒后Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='进入页静置10秒后Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertenheapsize',
            field=models.CharField(blank=True, default='', help_text='进入页静置10秒后Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='进入页静置10秒后Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertenobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='进入页静置10秒后Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='进入页静置10秒后Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertenobjectsviews',
            field=models.CharField(blank=True, default='', help_text='进入页静置10秒后Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='进入页静置10秒后Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertenpsstotal',
            field=models.CharField(blank=True, default='', help_text='进入页静置10秒后Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='进入页静置10秒后Pss Total内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertentwoheapalloc',
            field=models.CharField(blank=True, default='', help_text='进入页再次静置10秒后Heap Alloc内存（单位：KB）', max_length=100, null=True, verbose_name='进入页再次静置10秒后Heap Alloc内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertentwoheapfree',
            field=models.CharField(blank=True, default='', help_text='进入页再次静置10秒后Heap Free内存（单位：KB）', max_length=100, null=True, verbose_name='进入页再次静置10秒后Heap Free内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertentwoheapsize',
            field=models.CharField(blank=True, default='', help_text='进入页再次静置10秒后Heap Size内存（单位：KB）', max_length=100, null=True, verbose_name='进入页再次静置10秒后Heap Size内存'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertentwoobjectsactivities',
            field=models.CharField(blank=True, default='', help_text='进入页再次静置10秒后Objects Activities数（单位：个）', max_length=100, null=True, verbose_name='进入页再次静置10秒后Objects Activities数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertentwoobjectsviews',
            field=models.CharField(blank=True, default='', help_text='进入页再次静置10秒后Objects Viewss数（单位：个）', max_length=100, null=True, verbose_name='进入页再次静置10秒后Objects Viewss数'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='nextaftertentwopsstotal',
            field=models.CharField(blank=True, default='', help_text='进入页再次静置10秒后Pss Total内存（单位：KB）', max_length=100, null=True, verbose_name='进入页再次静置10秒后Pss Total内存'),
        ),
    ]
