# Generated by Django 2.0.5 on 2019-08-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0008_auto_20190806_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='meminfotestcase',
            name='dependcase',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='_meminfotestcase_dependcase_+', to='performancestatistics.MeminfoTestCase', verbose_name='依赖的用例ID'),
        ),
    ]
