# Generated by Django 2.0.5 on 2019-08-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0009_meminfotestcase_dependcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meminfotestcase',
            name='dependcase',
        ),
        migrations.AddField(
            model_name='meminfotestcase',
            name='dependcase',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='performancestatistics.MeminfoTestCase', verbose_name='依赖的用例ID'),
        ),
    ]
