# Generated by Django 2.0.5 on 2019-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancestatistics', '0010_auto_20190807_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='meminfotestresult',
            name='test_phone_model',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试手机型号'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='test_phone_resolution_ratio',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试手机分辨率'),
        ),
        migrations.AddField(
            model_name='meminfotestresult',
            name='test_phone_system_version',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试手机系统版本'),
        ),
    ]
