# Generated by Django 2.0.5 on 2019-05-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addticket',
            options={'verbose_name': '添加代金券测试数据', 'verbose_name_plural': '添加代金券测试数据'},
        ),
    ]
