# Generated by Django 2.0.5 on 2019-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0002_auto_20190529_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='addticket',
            name='kfyqthddj',
            field=models.CharField(blank=True, default='', help_text='1表示不可以叠加使用，为2表示可以叠加使用', max_length=100, null=True, verbose_name='输入可否与其他活动叠加的单选的内容'),
        ),
    ]
